name: gatt_the_bugger
description: GATT debugger
version: 0.2.0
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^1.0.1
  flutter_blue: ^0.8.0
  location: ^4.2.3
  shared_preferences: ^2.0.6
  wave: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4

flutter:
  uses-material-design: true
  assets:
    - bluetooth-numbers-database/v1/

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/appicon.png'

flutter_native_splash:
  color: '#303f9f'
