name: gatt_the_bugger
description: GATT debugger
version: 0.1.3
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_info: ^2.0.0
  flutter_blue: ^0.8.0
  location: ^4.1.1
  shared_preferences: ^2.0.5
  wave: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter:
  uses-material-design: true
  assets:
    - bluetooth-numbers-database/v1/

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/appicon.png'
